### PR TITLE
Fix UdpCodec::encode

### PR DESCRIPTION
**Pull request by kpp**
Change the signature of UdpCodec::encode
 
Now it is:
    
```
fn encode(&mut self, msg: Self::Out, buf: &mut Vec<u8>)
                                              -> Result<SocketAddr, Self::Error>;
```

Closes https://github.com/tokio-rs/tokio/issues/79

### CODE REVIEW

**Comment by carllerche** [comment]
I would suggest opening this on the tokio repo (not tokio-core) as this is a breaking change and cannot land in tokio-core 0.1.

**Comment by kpp** [comment]
@carllerche OK. But what's the difference between tokio and tokio_core?

**Comment by carllerche** [comment]
@kpp the `tokio` crate is basically going to be `tokio-core` 0.2.

**Comment by kpp** [comment]
So do I have to move from `tokio_core` to `tokio`?

**Comment by kpp** [comment]
> I would suggest opening this on the tokio repo (not tokio-core) as this is a breaking change and cannot land in tokio-core 0.1.

@carllerche here it is https://github.com/tokio-rs/tokio/pull/85

**Comment by alexcrichton** [comment]
Ok I'm gonna close this in favor of https://github.com/tokio-rs/tokio/pull/85, thanks for the PRs @kpp!

**Pull request closed without merging**
