### PR TITLE
Unboxing TcpStream

### PR DESCRIPTION
**Pull request by alreece45**
Fairly rough work to unbox TcpStream's methods for #133 

Don't expect this to merge, but hope that it'll help someone who can clean it up a bit more-- especially some of the type-work figured out.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Perhaps we could just explicitly encode the state machine here with:

```rust
enum Connect {
    Connecting(PollEvented<TcpStream>)
    Error(io::Error),
    Empty,
}
```

and then `poll` would transition amongst those?

**Comment by alreece45** [comment]
Have `Connect` be a public enum returned from `connect()` and `connect_stream()`?

That'd probably be simpler-- I resisted doing it because it changes the interface a bit more-- the enum would be public, more of the state would be exposed, and I don't have the expertise to know if that's a good decision in the long-term.

**Comment by alexcrichton** [comment]
Oh I think we can keep the enum private, it'd just be a minor implementation detail of the `TcpStreamNew` return value. We'd want to keep the same API for now and if we want to break it we can consider that for 0.2

**Comment by alexcrichton** [comment]
Ok I touched up a few of the commits here manually and merged, thanks again for the PR!

**Pull request merged**
