### PR TITLE
Make TimeoutToken public

### PR DESCRIPTION
**Pull request by en**
Just export TimeoutToken.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This type is intended to be private and in theory is superseded by the `Interval` and `Timeout` types, how come you need this public?

**Comment by en** [comment]
Hi, Alex! I implemented a custom type similar to `Interval`, but the interval is different in each iteration.

**Comment by alexcrichton** [comment]
Ah ok makes sense to me. Becaues this time is intended to be private, I wonder if we could add an approrpriate method to the `Timeout` type perhaps?

**Comment by en** [comment]
How about add this method to `Timeout`:
```
    pub fn reset(&mut self, at: Instant) {
        self.when = at;
        self.token.reset_timeout(self.when, &self.handle);
    }
```
So I can reuse a `Timeout` to implement a custom `Interval`.

**Comment by alexcrichton** [comment]
Yeah sounds great!

**Comment by en** [comment]
OK, I will submit a new PR.

**Pull request closed without merging**
