### PR TITLE
Polish tokio-core in prep for overall 0.1 release

### PR DESCRIPTION
**Pull request by aturon**
This commit makes a few tweaks to the new `easy` module:
- ~~Rename `Parse` to `Deserialize`, for symmetry with the `Serialize`
  trait.~~
- Rename `Parse` to `Decode` and `Serialize` to `Encode`.
- Don't use `Poll` for the `deserialize` method; we prefer to reserve
  that type for actual aync events, and in particular for a `NotReady`
  result to imply that some task scheduling has taken place. Instead,
  use an internal `Option`.

cc @carllerche @alexcrichton

### CODE REVIEW

**Comment by tailhook** [comment]
Looks good to me.

And if we are simplifying this thing, are there any good aliases for `In` and `Out` ? I mean it's often messed up because `In` looks like something that is read from the socket, but it's the opposite. Maybe `Source`, `Target` are good alternatives?

**Comment by alexcrichton** [comment]
👍

**Comment by carllerche** [comment]
Since this touches naming, do we want to consider using `Encode` / `Decode` instead? It is shorter and this is the terminology I've seen in the past.

**Comment by alexcrichton** [comment]
Hm yeah if I had to pick two names I like Encode/Decode, nice, short, accepted, etc.

**Comment by aturon** [comment]
@tailhook I do think we want to reconsider those names, but I'm trying to avoid any breakage against what's been published in 0.1 so far. The `FramedIo` trait is likely to be [re-thought entirely](https://github.com/tokio-rs/tokio-core/issues/66) in 0.2.

@carllerche @alexcrichton Yes, `encode`/`decode` is even better; I'll change it.

**Pull request merged**
